### ISSUE TITLE
tcall reads $FFC0-$FFFF as normal RAM memory regardless of IPL ROM flag

### ISSUE THREAD

**Issue by LMPuny** [dgrfactory/spcplay#24] opened 2021-02-16 19:08 UTC
in spcplay, tcall seems to ignore the r flag at $F1 (r-ba-210) which controls if $FFC0-$FFFF is IPL ROM or normal RAM, always treating it as the latter. this spcplay quirk is apparently not real SNES behaviour.

i stumbled upon this while trying to narrow down the cause of my spc files playing fine on spcplay, but not on anything else (i.e. foobar, and discord bots generating empty mp3 files out of my spc files). when i replaced every instance of tcall on my driver with generic call commands, it worked fine, and with help from KungFuFurby who used bsnes+, i discovered disabling the previously said flag would allow tcall to work properly so i can only blame spcplay for innacuracy here

**Comment by dgrfactory** [comment] 2021-02-17 12:38
Hi, @LMPuny
Thank you for reporting the issue.

I looked at the current code, it seems implemented consideration of the R flag of control.
When R flag is on, save values of RAM to extraRAM, so IPL code is copied to RAM address $FFC0-$FFFF.
This makes it appear to refer to IPL ROM when R flag is on.

Maybe this implementation is different from real, it seems to be implemented in this way to speed up from the first version.
Perhaps, this mimics the behavior of the old SNES emulator.

I made a test SPC and tried it, but problem not found.
Play attached test SPC, Y register is set to $02 if R flag is enabled, and set to $01 if disabled.
https://dgrfactory.jp/spcplay/test/tcall_test.spc

```
;Entrypoint address $0100 (in tcall_test.spc, $0200)
E8 80     ; MOV A,$80  (R is enabled)
C4 F1     ; MOV [dp0+$F1],A
F1        ; TCALL 15 = CALL [RAM+$EFCD]

;$EFCD (in tcall_test.spc, $F0CD)
FC        ; INC Y
FC        ; INC Y
FF        ; STOP  (Y = $02)
```

```
;Entrypoint address $0100 (in tcall_test.spc, $0200)
E8 00     ; MOV A,$00  (R is disabled)
C4 F1     ; MOV [dp0+$F1],A
F1        ; TCALL 15 = CALL [RAM+$0400]

;$0400 (in tcall_test.spc, $0500)
FC        ; INC Y
FF        ; STOP  (Y = $01)
```

However, SPC with address $F1 set to $80 from first may cause this issue.
This is because the above behavior assumes that the address $100C0-$100FF in SPC file has same as IPL ROM when R flag is on.

I think there is a bug in SNESAPU initialization process rather than TCALL, but I am not sure.
If you have SPC file that shows this issue immediately, please attach it if possible.

**Comment by dgrfactory** [comment] 2021-02-18 12:50
I do not know if it fits your pattern, but I fixed initialization process of SNESAPU which seems to be the cause.
Please download and try the fixed SNESAPU at the link below.
https://github.com/dgrfactory/spcplay/releases/download/2.18.3.7249/snesapu-2.18.3.7258.zip

If not fixed, the cause is currently unknown, I look forward to hearing from you.
Thanks.

**Comment by dgrfactory** [comment] 2021-03-14 09:05
Released.
https://github.com/dgrfactory/spcplay/releases/tag/2.18.3.7258

**Closed as completed by dgrfactory** 2021-03-14 09:05 UTC
Labels: bug, fixed
